Fix pop response return value
dgretton/pyhamilton pull request #20
Opened 2022-11-24 07:55 UTC by ysimenya

This is an attempt to unify the output of `wait_on_response()`
The returned `module_id` is in some cases (namely, for the ph_dryer, module_id = 100 and is != 0 or 1) is not correct.

I've elected to emit the message `HamiltonResponse` that groups all data related to the server response.
I understand this may be a deal breaker for projects using pyhamilton as those expect a boolean or tuple or a list.
Still, exception are raised as previously.

What do you think?

Kr,
Ysi

2022-11-28 05:37 UTC, stefangolas commented
This is a pretty substantial change to the HamiltonInterface class. I'll have to review this pretty thoroughly which might take some time. I am willing to give it a shot if it seems to be a better design in the long run.

2022-11-28 23:31 UTC, stefangolas requested changes
Excellent work, really thanks very much for taking the time to make this. There are some small changes I request but otherwise this is a very valuable contribution to the library.

2022-11-28 23:31 UTC, stefangolas commented on pyhamilton/interface.py
> +                    "{numField:d},{mainErrField:d},{slaveErr:d},{recoveryBtnId:d},{stepData},{labwareName:w},{labwarePos:w}",
This line causes a HamiltonReturnParseError to get raised by line 400 when I run the initialize function:
`parse("{numField:d},{mainErrField:d},{slaveErr:d},{recoveryBtnId:d},{stepData},{labwareName:w},{labwarePos:w}"`

 This is because `initialize` only returns 6 fields instead of 7, causing parse(...) to return None. Unfortunately the type of response strings that Venus returns can have a few different formats, so we have to be flexible and maybe have a few different formats for parse.

This would work by the way: `parse("{numField:d},{mainErrField:d},{slaveErr:d},{recoveryBtnId:d},{stepData},{labwareName:w}")`

I strongly recommend to test the template method created by `pyhamilton-new-project` to make sure the basic functions of PyHamilton still work.

2022-12-02 21:24 UTC, ysimenya commented on pyhamilton/interface.py
> +                    "{numField:d},{mainErrField:d},{slaveErr:d},{recoveryBtnId:d},{stepData},{labwareName:w},{labwarePos:w}",
Thanks Stefan!
The issue is fixed so that we don't need to hardcode the expected number of fields in a valid block.
Also:
 - [x] Unit test added for that case
 - [x]  `pyhamiton-new-project` runs just fine ;-)

2022-12-02 21:28 UTC, ysimenya commented
I have updated the PR that fixes `initialize()` parse error.
I didn't change the package version as I am not sure to which one we should jump to ...

Kr,
Ysi

2022-12-02 21:33 UTC, stefangolas commented
Thank you! I will update the version number myself.

On Fri, Dec 2, 2022 at 4:28 PM Yves Simenya ***@***.***>
wrote:

> I have updated the PR that fixes initialize() parse error.
> I didn't change the package version as I am not sure to which one we
> should jump to ...
>
> Kr,
> Ysi
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dgretton/pyhamilton/pull/20#issuecomment-1335860362>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHXPLLUFKUBLEZRWE3QSI4TWLJSWVANCNFSM6AAAAAASJ52YNY>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-12-05 05:39 UTC, merged